gui:
  theme:
    activeBorderColor:
      - '#ceacf6'
      - bold
    inactiveBorderColor:
      - '#6e6a86'
    optionsTextColor:
      - '#ceacf6'
    selectedLineBgColor:
      - '#26233a'
    cherryPickedCommitBgColor:
      - '#403d52'
    cherryPickedCommitFgColor:
      - '#ceacf6'
    unstagedChangesColor:
      - '#eb6f92'
    defaultFgColor:
      - '#e0def4'
    searchingActiveBorderColor:
      - '#f6c177'
  authorColors:
    '*': '#ceacf6'
